volumes:
  jwtdown-db-data:
    external: true
  dishdynamo-data:
    external: true
services:

  fastapi:
    build:
      context: ./dishdynamo
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://user:secret@db/dishdynamopostgres
      WAIT_HOSTS: db:5432
      PORT: 8000
      SIGNING_KEY: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4MDEzMTg5OSwiaWF0IjoxNjgwMTMxODk5fQ.wcQF_Fy9OfiLJRPs0m1NtK6vhMjoAC48ok5qtb_c9R4

      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60

    ports:
      - 8000:8000
    volumes:
      - ./dishdynamo:/app
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: dishdynamopostgres
    ports:
      - "15432:5432"
    volumes:
      - dishdynamo-data:/var/lib/postgresql/data

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
